name: Build & Push Sympa image

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - config/**
      - entrypoint.sh

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nico-l/sympa

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/nico-l/sympa:latest
